### PR TITLE
Adding docker  + protractor docs to cookbook.

### PR DESCRIPTION
**Pull request by jags14385**
Adding the documentation to the cookbook .

Let me know, if anything else needs to be added.

### CODE REVIEW

**Comment by jags14385** [comment]
@cnishina Do, I need to do something else to be able to merge this PR?

**Comment by cnishina** [comment]
@googlebot cla?

**Comment by cnishina** [comment]
@googlebot

**Comment by cnishina** [comment]
It appears I did not have @googlebot turned on... this does require signing the cla. Please resubmit this PR. This is definitely a great addition.

**Pull request closed without merging**
